import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../ultils/requests";

const Home = ({ results }) => {
  return (
    <div>
      <Head>
        <title>Movie_Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results results={results} />
    </div>
  );
};

Home.getInitialProps = async (context) => {
  console.log("request");
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  );
  let response = await request.json();
  return {
    results: response ? response : {},
  };
};

export default Home;
